image: laurentdoguin/gitpod-workspacefull-couchbase

tasks:
  - name: Install dependencies
    init: |
      sudo rm -rf ~/.npm/ && npm install && gp sync-done installdep
  - name : Import Couchbase sample bucket
    command: |
      gp await-port 8091
      CB_SAMPLES='["travel-sample"]' /scripts/import-sample-buckets.sh
  - name: Start Couchbase Server
    command: |
      sudo runsvdir -P /etc/service
  - name: Start Server
    init: gp sync-await installdep
    command: |
      gp await-port 8091
      npm run dev

# exposed ports
ports:
- port: 4000 # NodeJS Apollo Server
  onOpen: open-browser
  visibility: public
- port: 8091 # Couchbase Web console, REST/HTTP interface
  onOpen: open-browser
  visibility: public
- port: 8092 # Views, queries, XDCR
  onOpen: ignore
- port: 8093 # Query services (4.0+)
  onOpen: ignore
- port: 8094 # Full-text Search (4.5+)
  onOpen: ignore
- port: 8095 # Analytics (5.5+)
  onOpen: ignore
- port: 8096 # Eventing (5.5+)
  onOpen: ignore
- port: 11207 # Smart client library data node access (SSL)
  onOpen: ignore
- port: 11210 # Smart client library/moxi data node access
  onOpen: ignore
- port: 11211 # Legacy non-smart client library data node access
  onOpen: ignore
- port: 18091 # Couchbase Web console, REST/HTTP interface (SSL)
  onOpen: ignore
- port: 18092 # Views, query, XDCR (SSL)
  onOpen: ignore
- port: 18093 # Query services (SSL) (4.0+)
  onOpen: ignore
- port: 18094 # Full-text Search (SSL) (4.5+)
  onOpen: ignore
- port: 18095 # Analytics (SSL) (5.5+)
  onOpen: ignore
- port: 18096 # Eventing (SSL) (5.5+)
  onOpen: ignore
- port: 4369
  onOpen: ignore
- port: 5990
  onOpen: ignore
- port: 6942
  onOpen: ignore
- port: 9100
  onOpen: ignore
- port: 9101
  onOpen: ignore
- port: 9102
  onOpen: ignore
- port: 9103
  onOpen: ignore
- port: 9104
  onOpen: ignore
- port: 9105
  onOpen: ignore
- port: 9110
  onOpen: ignore
- port: 9111
  onOpen: ignore
- port: 9112
  onOpen: ignore
- port: 9113
  onOpen: ignore
- port: 9115
  onOpen: ignore
- port: 9116
  onOpen: ignore
- port: 9117
  onOpen: ignore
- port: 9118
  onOpen: ignore
- port: 9119
  onOpen: ignore
- port: 9120
  onOpen: ignore
- port: 9121
  onOpen: ignore
- port: 9122
  onOpen: ignore
- port: 9123
  onOpen: ignore
- port: 9130
  onOpen: ignore
- port: 9998
  onOpen: ignore
- port: 9999
  onOpen: ignore
- port: 11206
  onOpen: ignore
- port: 11209
  onOpen: ignore
- port: 11280
  onOpen: ignore
- port: 19102
  onOpen: ignore
- port: 19130
  onOpen: ignore
- port: 21100
  onOpen: ignore
- port: 21200
  onOpen: ignore
- port: 21300
  onOpen: ignore
- port: 36173
  onOpen: ignore
- port: 39969
  onOpen: ignore
- port: 41135
  onOpen: ignore
- port: 41209
  onOpen: ignore
- port: 63342
  onOpen: ignore
