image: laurentdoguin/gitpod-workspacefull-couchbase

tasks:
  - init: |
      npm install
  - command: |
      node index.js

# exposed ports
ports:
- port: 8091
  onOpen: open-preview
- port: 8092-10000
  onOpen: ignore
- port: 4369
  onOpen: ignore
