image: laurentdoguin/gitpod-workspacefull-couchbase

tasks:
  - name: Start Couchbase Server
    init: |
      sudo runsvdir -P /etc/service 
  - name: Install dependencies
    init: |
      npm install
  - name: Start Server
    command: |
      gp await-port 8091
      node index.js

# exposed ports
ports:
- port: 8091 # Couchbase Web console, REST/HTTP interface
  onOpen: open-preview
- port: 8092 # Views, queries, XDCR
  onOpen: ignore
- port: 8093 # Query services (4.0+)
  onOpen: ignore
- port: 8094 # Full-text Search (4.5+)
  onOpen: ignore
- port: 8095 # Analytics (5.5+)
  onOpen: ignore
- port: 8096 # Eventing (5.5+)
  onOpen: ignore
- port: 11207 # Smart client library data node access (SSL)
  onOpen: ignore
- port: 11210 # Smart client library/moxi data node access
  onOpen: ignore
- port: 11211 # Legacy non-smart client library data node access
  onOpen: ignore
- port: 18091 # Couchbase Web console, REST/HTTP interface (SSL)
  onOpen: ignore
- port: 18092 # Views, query, XDCR (SSL)
  onOpen: ignore
- port: 18093 # Query services (SSL) (4.0+)
  onOpen: ignore
- port: 18094 # Full-text Search (SSL) (4.5+)
  onOpen: ignore
- port: 18095 # Analytics (SSL) (5.5+)
  onOpen: ignore
- port: 18096 # Eventing (SSL) (5.5+)
  onOpen: ignore
