image: laurentdoguin/gitpod-workspacefull-couchbase

tasks:
  - name: Install dependencies
    init: |
      npm install && gp sync-done installdep
  - name : Import Couchbase sample bucket
    command: |
      gp await-port 8091
      CB_SAMPLES='["travel-sample"]' /scripts/import-sample-buckets.sh
  - name: Start Couchbase Server
    command: |
      sudo runsvdir -P /etc/service
  - name: Start Server
    init: gp sync-await installdep
    command: |
      gp await-port 8091
      node index.js

# exposed ports
ports:
- port: 8091 # Couchbase Web console, REST/HTTP interface
  onOpen: open-preview
- port: 8092 # Views, queries, XDCR
  onOpen: ignore
- port: 8093 # Query services (4.0+)
  onOpen: ignore
- port: 8094 # Full-text Search (4.5+)
  onOpen: ignore
- port: 8095 # Analytics (5.5+)
  onOpen: ignore
- port: 8096 # Eventing (5.5+)
  onOpen: ignore
- port: 11207 # Smart client library data node access (SSL)
  onOpen: ignore
- port: 11210 # Smart client library/moxi data node access
  onOpen: ignore
- port: 11211 # Legacy non-smart client library data node access
  onOpen: ignore
- port: 18091 # Couchbase Web console, REST/HTTP interface (SSL)
  onOpen: ignore
- port: 18092 # Views, query, XDCR (SSL)
  onOpen: ignore
- port: 18093 # Query services (SSL) (4.0+)
  onOpen: ignore
- port: 18094 # Full-text Search (SSL) (4.5+)
  onOpen: ignore
- port: 18095 # Analytics (SSL) (5.5+)
  onOpen: ignore
- port: 18096 # Eventing (SSL) (5.5+)
  onOpen: ignore
- port: 4369
  onOpen: ignore
- port: 5990
  onOpen: ignore
- port: 6942
  onOpen: ignore
- port: 9100-9999
  onOpen: ignore
- port: 11206-9999
  onOpen: ignore
4369
5990
6942
9100
9101
9102
9110
9111
9112
9113
9115
9116
9117
9118
9119
9120
9121
9122
9123
9130
9998
9999
11206
11209
11280
19102
19130
21100
21200
21300
36173
39969
41135
41209
63342